### ISSUE TITLE
Red color is wider than the purple by one third

### ISSUE THREAD

**Issue by elnormous** [spacekookie/gay#1]
In the flag of LGBT all the colors are equal width. Here the red color (and also the other ones) is a lot wider than the purple color. I understand that this is done to maintain the order of the colors, but you should reduce the file size of all the colors until that are almost equal.

**Comment by drewcassidy** [comment]
...that is an extremely unfortunate typo

**Comment by elnormous** [comment]
Just fixed it (the typo was in the word "flag" :D).

**Comment by spacekookie** [comment]
And I fixed the colour issue, red is now much closer to the others :)
