### ISSUE TITLE
What is this wastage?

### ISSUE THREAD

**Issue by ParthaEth** [spacekookie/gay#4]
Stop wasting energy by hosting nonsense code in public servers! And it has 182 stars! Are you serious? I understand that you want to support LGBTQ cause and that is important but this is no way and its not making a point in the right direction.

**Comment by ghost** [comment]
If GitHub gave a shit, they would remove it. If you have a problem with it, then leave. Your disgusting.

**Comment by nathfreder** [comment]
Unless your paying for GitHub's servers, you don't have a say.

**Comment by backspace** [comment]
I find it quite unlikely that you’re making an environmentalist argument here rather than using one as a cover for anti-queer/anti-trans sentiments.

**Comment by ParthaEth** [comment]
LOL stop saying 'shit' and start making arguments. I fail to see how you make any point. This is not even a list of what you want to do and what have you done for LGBTQ. Is there a argument why this should be there in GIT at all other than increasing the entropy (Thermodynamic) of the world.

**Comment by backspace** [comment]
If you actually believed this was wasteful, you’d stop commenting, which is itself consuming energy.

**Comment by spacekookie** [comment]
@ParthaEth would you kindly fuck off? Thank you
